---
- name: Create Caddyfile
  blockinfile: 
    create: yes
    path: /home/docker/caddy/Caddyfile
    block: |
        {
            # Global options block. Entirely optional, https is on by default
            # Optional email key for lets encrypt
            email <letsencrypt_email>
            # Optional staging lets encrypt for testing. Comment out for production.
            # acme_ca https://acme-staging-v02.api.letsencrypt.org/directory
        }
        <nautobot_domain> {
            reverse_proxy nautobot:80
            encode zstd gzip
        }