
- name: Create Nautobot tenant
  networktocode.nautobot.tenant:
    url: "{{ nb_url }}"
    token: "{{ nb_token }}"
    name: "{{ clientcode }}"
    description: "{{ clientdescription }}"
    state: present
  register: nb_tenant

- name: "Print tenant output"
  debug:
    msg: "{{ nb_tenant }}"
  when: show_debug | bool